### ISSUE TITLE
Implement Cost Centers

### ISSUE THREAD

**Issue by AlexTheWizardL** [macxred/pyledger#95]
### Key concepts:

- “Profit center” (aka “cost center”) is an additional dimension for classifying ledger entries, i.e. an optional column in the ledger schema.
- Users can define a discrete list of profit centers (strings)
    - If users work with profit centers, each ledger entry NEEDS to be attributed to exaclty one out of the list of predefined profit centers. 
    - If users do not work with profit centers (none are defined), ledger entries are not attributed to any profit center, the column is not added to TextLedger.
- Method to query or summarize ledger entries, such as account balance and account history, can optionally filter ledger entries by one or more profit centers. By default, they return ledger entries regardless of the profit center assigned.

### Code implementation sketches: 
- `cost_centers: list[str] | str = None` : Filter for ledger entries. If not None, the result is calculated only from ledger entries assigned to one of the cost centers in the filter.
- `account_history` and `account_balance` shall raise a warning if an item in the cost center filter is not defined in the cost center accounting entity.

### Note:

Update for `sanitize_ledger()` method If the const center entity is not empty, ledger entries must have none-missing cost center entries and each entry must mach an entry in the cost center accounting entity. If violated, discard the ledger entry.

### Implementation Steps:

- [x] Implement Cost Centers entity in `PyLedger` package
- [ ] Implement logic for `account_history` with new Cost Centers entity
- [ ] Test above functionality using base test
- [ ] Implement cost centers entity for `CashCtrlLedger`
- [ ] Implement logic for `account_history` with new Cost Centers entity for  `CashCtrlLedger`
- [ ] Test this logic using base tests from `PyLedger` package

**Comment by AlexTheWizardL** [comment]
Cost centers should be renamed to profit centers
